Repository wecode-bootcamp-korea/11-PrettyCloud-frontend, pull requests merged in 2020-09, with the labels that each got.

#2 [조윤민] Add: searchResult page 상단 레이아웃
  .eslintrc.json
  package-lock.json
  package.json
  public/images/all_icon.png
  public/images/expand_arrow.png
  public/images/max_user.png
  public/images/redCheck.png
  public/images/space.jpeg
  src/Pages/SearchResult/SearchResult.js
  src/Pages/SearchResult/SearchResult.scss
  src/Pages/SearchResult/SpaceCard.js
  src/Pages/SearchResult/SpaceCard.scss
  src/Pages/SearchResult/SpaceList.js
  src/Pages/SearchResult/SpaceList.scss
  src/Routes.js
  src/index.js
Labels: Status: Accepted

#6 [조윤민] Add: product list 레이아웃
  public/data/data.json
  src/Pages/SearchResult/NormalZone.js
  src/Pages/SearchResult/NormalZone.scss
  src/Pages/SearchResult/PlusZone.js
  src/Pages/SearchResult/PlusZone.scss
  src/Pages/SearchResult/PremiumZone.js
  src/Pages/SearchResult/PremiumZone.scss
  src/Pages/SearchResult/SearchResult.js
  src/Pages/SearchResult/SearchResult.scss
  src/Pages/SearchResult/SpaceCard.js
  src/Pages/SearchResult/SpaceCard.scss
Labels: Status: 리뷰 요청

#7 [김영지]Add: AsideNav바 기능 추가
  src/Components/AsideNav.js
  src/Components/AsideNav.scss
  src/Components/Nav.js
Labels: Status: 리뷰 요청

#11 [김영지]Add: 검색기능 추가
  src/Components/AsideNav.js
  src/Components/Nav.js
  src/Pages/Login/Login.js
  src/Pages/Login/SignUp.scss
Labels: Status: 리뷰 요청

#9 [김영지]Modify : 리뷰사항 수정
  public/data/reservation.json
  src/Pages/Login/Login.js
  src/Pages/ReservationList/Reservation.js
  src/Pages/ReservationList/Reservation.scss
  src/Pages/ReservationList/ReservationList.js
  src/Pages/ReservationList/ReservationList.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#10 [조윤민] Add: fetch( )를 이용하여 API 호출
  public/data/data.json
  src/Components/Footer.js
  src/Components/Nav.js
  src/Config/urls.js
  src/Pages/Login/Login.js
  src/Pages/SearchResult/NormalZone.js
  src/Pages/SearchResult/NormalZone.scss
  src/Pages/SearchResult/PlusZone.js
  src/Pages/SearchResult/PremiumZone.js
  src/Pages/SearchResult/ResultFrame.js
  src/Pages/SearchResult/ResultFrame.scss
  src/Pages/SearchResult/SearchResult.js
  src/Pages/SearchResult/SearchResult.scss
  src/Pages/SearchResult/SpaceCard.js
  src/Pages/SearchResult/SpaceCard.scss
  src/Pages/SearchResult/SpaceList.js
  src/Pages/SearchResult/SpaceList.scss
  src/config.js
Labels: Status: Accepted

#8 [김영지] Fix: 충돌해결
  package-lock.json
  package.json
  src/Components/AsideNav.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/SignUp.js
  src/Pages/Login/SignUp.scss
  src/config.js
Labels: Status: Accepted

#3 [조은별] Add: Detail 페이지 동적라우팅
  public/data/detail.json
  public/images/heart.png
  public/images/logo192.jpg
  public/images/share.png
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/DetailList.js
  src/Pages/Detail/DetailList.scss
  src/Pages/Detail/DetailNav.js
  src/Pages/Detail/DetailNav.scss
  src/Pages/Detail/Facility.js
  src/Pages/Detail/Facility.scss
  src/Pages/Detail/Refund.js
  src/Pages/Detail/Refund.scss
  src/Pages/Detail/Reservation.js
  src/Pages/Detail/Reservation.scss
  src/Pages/Detail/Review.js
  src/Pages/Detail/Review.scss
  src/Pages/Detail/ReviewComment.js
  src/Pages/Detail/ReviewComment.scss
  src/Pages/Detail/SpaceInfo.js
  src/Pages/Detail/SpaceInfo.scss
  src/Pages/Detail/Tags.js
  src/Pages/Detail/Tags.scss
  src/Pages/SearchResult/NormalZone.js
  src/Pages/SearchResult/PlusZone.js
  src/Pages/SearchResult/PremiumZone.js
  src/Pages/SearchResult/SpaceCard.js
  src/Routes.js
Labels: Status: 리뷰 요청

#13 [김영지]add: 로그인 로그아웃 추가
  src/Pages/Login/Login.js
  src/Pages/Login/SignUp.js
  src/Pages/Login/SignUp.scss
Labels: Status: 리뷰 요청

#5 [박진아] Add:main 레이아웃 추가
  package-lock.json
  package.json
  public/Data/categories.json
  public/Data/main.json
  public/Data/mainSlider.json
  public/Data/recommendation.json
  public/Data/userReview.json
  src/Pages/Main/Components/RecommendSpace/RecommendSpace.js
  src/Pages/Main/Components/RecommendSpace/RecommendSpace.scss
  src/Pages/Main/Components/RecommendSpace/SpaceCard.js
  src/Pages/Main/Components/RecommendSpace/SpaceCard.scss
  src/Pages/Main/Components/SliderPanel/SlideCard.js
  src/Pages/Main/Components/SliderPanel/SlideCard.scss
  src/Pages/Main/Components/SliderPanel/SliderPanel.js
  src/Pages/Main/Components/SliderPanel/SliderPanel.scss
  src/Pages/Main/Components/UserReview/UserReview.js
  src/Pages/Main/Components/UserReview/UserReview.scss
  src/Pages/Main/Components/UserReview/UserReviewCard.js
  src/Pages/Main/Components/UserReview/UserReviewCard.scss
  src/Pages/Main/Components/jina.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/config.js
Labels: Status: 수정 요청
